services:
  frontend:
    build: ./web-frontend
    ports:
      - "3000:3000"
    environment:
      - ENDPOINT=http://localhost:3333
      - BACKEND_CONTAINER=http://website-backend:3333
    depends_on:
      - backend
    container_name: website-frontend
    networks:
      - network-bridge
  backend:
    build: ./web-backend
    ports:
      - "3333:3333"
    env_file:
      - path: ./web-backend/.env
        required: true
    environment:
      - PORT=3333
    container_name: website-backend
    networks:
      - network-bridge
networks:
  network-bridge:
    driver: bridge
